name: cashback
description: "A new Flutter project for cashback."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Add these dependencies for SQLite:
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.18.1
  fl_chart: ^0.65.0
  yahoofin: ^0.0.8
  csv: ^5.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # --- ADD THIS SECTION ---
  assets:
    - assets/synthetic_personal_finance_dataset.csv
  # --- END OF SECTION ---